:bug:(ozi-fix): Fix missing ``run_utility`` AttributeError
Fixes: File "<OZI-0.0.198>/ozi/fix.py", line 667, in main
AttributeError: 'Namespace' object has no attribute 'run_utility'